//! Buchberger's algorithm, and the gcd / lcm / rational-reduction it backs.
//!
//! The pair polynomial `h_ij` is the S-polynomial of `gᵢ` and `gⱼ` reduced by
//! the whole basis. The pairs are held in a table rather than a queue because
//! adding a generator can only *shrink* the set of pairs that still reduce to
//! something: a pair that already reduced to zero stays zero, so the table only
//! recomputes entries that did not.
//!
//! `lcm` comes from the ideal intersection `⟨t·f, (1−t)·g⟩ ∩ k[x]`: eliminate
//! the auxiliary variable `_t` by taking the one basis element that does not
//! mention it. `gcd` then follows from `f·g = gcd·lcm`.

use super::arith::{polynomial_mul, polynomial_sub};
use super::divide::{make_monic, poly_div, reduce};
use super::mono::{initial_term, mono_div, mono_gcd, mono_less_than, mono_to_poly, sum_monomials};
use super::rep::{same_var, Mono, Poly};
use crate::expr::Expr;
use crate::num::Number;
use std::collections::HashMap;

/// The S-polynomial of `polys[i]` and `polys[j]`, reduced by the whole list.
fn hij(i: usize, j: usize, polys: &[Poly]) -> Poly {
    let (init_i, init_j) = (initial_term(&polys[i]), initial_term(&polys[j]));
    let gcd = mono_gcd(&init_i, &init_j);
    let (Some(mij), Some(mji)) = (mono_div(&init_i, &gcd), mono_div(&init_j, &gcd)) else {
        return Poly::zero();
    };
    let s = polynomial_sub(
        &polynomial_mul(&mono_to_poly(&mji), &polys[i]),
        &polynomial_mul(&mono_to_poly(&mij), &polys[j]),
    );
    poly_div(&s, polys).1
}

/// The next generator to add: the candidate with the smallest leading term, or
/// `1` as soon as one of them is a unit.
fn choice_lowest_degree(candidates: &[Poly]) -> Poly {
    let inits: Vec<Mono> = candidates.iter().map(initial_term).collect();
    let mut best = 0;
    for i in 1..candidates.len() {
        if matches!(&inits[i], Mono::Coeff(Expr::Num(Number::Int(1)))) {
            return Poly::one();
        }
        if mono_less_than(&inits[i], &inits[best]) {
            best = i;
        }
    }
    candidates[best].clone()
}

type Table = HashMap<(usize, usize), Poly>;

/// Fill the table for every pair, and return the first generator to add.
fn build_table(table: &mut Table, polys: &[Poly]) -> Option<Poly> {
    let mut candidates = Vec::new();
    for j in 1..polys.len() {
        for i in 0..j {
            let h = hij(i, j, polys);
            if !h.is_literal_zero() {
                candidates.push(h.clone());
            }
            table.insert((i, j), h);
        }
    }
    (!candidates.is_empty()).then(|| choice_lowest_degree(&candidates))
}

/// Append `h` to the basis, refresh the pairs that had not yet reduced to zero,
/// add the pairs against `h`, and return the next generator to add.
fn update_table(table: &mut Table, polys: &mut Vec<Poly>, h: Poly) -> Option<Poly> {
    let len = polys.len();
    polys.push(h);

    let mut candidates = Vec::new();
    for j in 1..len {
        for i in 0..j {
            if table.get(&(i, j)).is_some_and(|e| e.is_literal_zero()) {
                continue;
            }
            let h = hij(i, j, polys);
            if !h.is_literal_zero() {
                candidates.push(h.clone());
            }
            table.insert((i, j), h);
        }
    }
    for i in 0..len {
        let h = hij(i, len, polys);
        if !h.is_literal_zero() {
            candidates.push(h.clone());
        }
        table.insert((i, len), h);
    }

    (!candidates.is_empty()).then(|| choice_lowest_degree(&candidates))
}

/// The reduced Gröbner basis of the ideal generated by `polys`.
pub fn reduced_grobner(polys: &[Poly]) -> Vec<Poly> {
    let mut basis = reduce(polys);
    let mut table = Table::new();
    let mut h = build_table(&mut table, &basis);
    while let Some(next) = h {
        h = update_table(&mut table, &mut basis, next);
    }
    reduce(&basis)
}

/// The auxiliary elimination variable used by [`poly_lcm`].
///
/// Two requirements, and the second is easy to miss. It has to be a variable
/// the inputs cannot carry — and it has to sort *first* under
/// [`cmp_var`](super::rep::cmp_var), because a `Poly::Rec` is written in its
/// least variable and `poly_lcm` eliminates by rejecting the basis elements
/// whose leading variable is this one. The JS engine spelled it `_t`, which
/// fails the second requirement: the default order compares symbol names
/// byte-wise, so `"A" < "_t"`, and `poly_gcd`/`reduce_rational_expression` then
/// returned a basis element still carrying `_t` for *any* variable ordering
/// before `_` — every uppercase name. `reduce_rational_expression` on
/// `(A²−1)/(A²+2A+1)` answered `1/1` rather than `(A−1)/(A+1)`.
///
/// A leading control character sorts below every character a parser will accept
/// in a name, which satisfies both requirements at once.
fn aux_var() -> Expr {
    Expr::sym("\u{1}t")
}

/// The least common multiple of `f` and `g`.
pub fn poly_lcm(f: &Poly, g: &Poly) -> Option<Poly> {
    let t = Poly::Rec {
        var: aux_var(),
        terms: vec![(1, Poly::one())],
    };
    let one_minus_t = Poly::Rec {
        var: aux_var(),
        terms: vec![(0, Poly::one()), (1, Poly::Coeff(Expr::int(-1)))],
    };
    let basis = reduced_grobner(&[polynomial_mul(&t, f), polynomial_mul(&one_minus_t, g)]);

    for b in &basis {
        // A unit in the basis means the intersection is everything.
        if !b.is_rec() {
            return Some(Poly::one());
        }
        if !same_var(b.var(), &aux_var()) {
            return Some(b.clone());
        }
    }
    None
}

/// The greatest common divisor of `f` and `g`, with leading coefficient 1,
/// recovered from `f·g = gcd·lcm`.
pub fn poly_gcd(f: &Poly, g: &Poly) -> Option<Poly> {
    let lcm = poly_lcm(f, g)?;
    let (quotient, _) = poly_div(&polynomial_mul(f, g), &[lcm]);
    Some(make_monic(&sum_monomials(&quotient)))
}

/// `f / d` where `d` is known to divide `f` exactly.
pub fn poly_by_divisor(f: &Poly, d: &Poly) -> Poly {
    sum_monomials(&poly_div(f, std::slice::from_ref(d)).0)
}

/// Cancel the common factor of a rational expression's numerator and
/// denominator, and scale both so the denominator's leading coefficient is 1.
pub fn reduce_rational_expression(top: &Poly, bottom: &Poly) -> Option<(Poly, Poly)> {
    let gcd = poly_gcd(top, bottom)?;
    // The denominator's leading coefficient divides out of both sides too —
    // that is what makes the answer canonical rather than merely reduced.
    let denom_coeff = initial_term(bottom).coeff().clone();
    let div = polynomial_mul(&gcd, &Poly::Coeff(denom_coeff));
    Some((poly_by_divisor(top, &div), poly_by_divisor(bottom, &div)))
}
