//! Fixture-driven text parser tests.
//! - *-ast.json / *-errors.json: extracted from the JS spec data maps by
//!   scripts/extract-fixtures.mjs.
//! - *-edge.json: generated by running the JS parser as an oracle on an
//!   edge-case corpus (scripts/generate-edge-fixtures.mjs), covering lexer
//!   rules the upstream specs never exercise.
//!
//! Do not edit fixture files by hand.

mod common;

use math_expressions::{TextToAst, TextToAstOptions};

fn parse(input: &str) -> Result<math_expressions::Expr, math_expressions::ParseError> {
    TextToAst::new(TextToAstOptions::default()).convert(input)
}

#[test]
fn text_to_ast_fixtures() {
    common::run_tree_cases(include_str!("fixtures/text-to-ast.json"), parse);
}

#[test]
fn text_to_ast_error_fixtures() {
    common::run_error_cases(include_str!("fixtures/text-to-ast-errors.json"), parse);
}

#[test]
fn text_to_ast_edge_fixtures() {
    common::run_tree_cases(include_str!("fixtures/text-to-ast-edge.json"), parse);
}
