// Import exactly the functions that are needed from mathjs so that tree-shaking can reduce the bundle size.
import {
  create,
  // Arithmetic
  absDependencies,
  addDependencies,
  addScalarDependencies,
  subtractDependencies,
  subtractScalarDependencies,
  multiplyDependencies,
  multiplyScalarDependencies,
  divideDependencies,
  divideScalarDependencies,
  powDependencies,
  modDependencies,
  unaryMinusDependencies,
  unaryPlusDependencies,
  // Rounding & sign
  ceilDependencies,
  floorDependencies,
  roundDependencies,
  fixDependencies,
  signDependencies,
  // Comparison
  equalDependencies,
  equalScalarDependencies,
  largerDependencies,
  smallerDependencies,
  largerEqDependencies,
  smallerEqDependencies,
  unequalDependencies,
  // Logic
  andDependencies,
  andTransformDependencies,
  orDependencies,
  orTransformDependencies,
  notDependencies,
  xorDependencies,
  // Exponential/log
  expDependencies,
  expm1Dependencies,
  logDependencies,
  log1pDependencies,
  log2Dependencies,
  log10Dependencies,
  // Roots/power
  sqrtDependencies,
  cbrtDependencies,
  nthRootDependencies,
  nthRootsDependencies,
  squareDependencies,
  cubeDependencies,
  hypotDependencies,
  // Trig
  sinDependencies,
  cosDependencies,
  tanDependencies,
  asinDependencies,
  acosDependencies,
  atanDependencies,
  atan2Dependencies,
  secDependencies,
  cscDependencies,
  cotDependencies,
  asecDependencies,
  acscDependencies,
  acotDependencies,
  // Hyperbolic
  sinhDependencies,
  coshDependencies,
  tanhDependencies,
  asinhDependencies,
  acoshDependencies,
  atanhDependencies,
  sechDependencies,
  cschDependencies,
  cothDependencies,
  asechDependencies,
  acschDependencies,
  acothDependencies,
  // Special functions
  gammaDependencies,
  lgammaDependencies,
  erfDependencies,
  factorialDependencies,
  combinationsDependencies,
  permutationsDependencies,
  gcdDependencies,
  lcmDependencies,
  // Complex numbers
  reDependencies,
  imDependencies,
  argDependencies,
  conjDependencies,
  complexDependencies,
  ComplexDependencies,
  // Number types
  numberDependencies,
  fractionDependencies,
  FractionDependencies,
  numericDependencies,
  booleanDependencies,
  stringDependencies,
  BigNumberDependencies,
  bignumberDependencies,
  // Type utilities
  typeOfDependencies,
  cloneDependencies,
  formatDependencies,
  // Type checks
  isIntegerDependencies,
  isNaNDependencies,
  isFiniteDependencies,
  isZeroDependencies,
  isNegativeDependencies,
  isPositiveDependencies,
  isNumericDependencies,
  hasNumericValueDependencies,
  isBoundedDependencies,
  // Min/max
  minDependencies,
  maxDependencies,
  sumDependencies,
  // Matrix (for det, trace)
  detDependencies,
  traceDependencies,
  matrixDependencies,
  MatrixDependencies,
  DenseMatrixDependencies,
  SparseMatrixDependencies,
  // Constants
  eDependencies,
  piDependencies,
  iDependencies,
  EDependencies,
  PIDependencies,
  LN2Dependencies,
  LN10Dependencies,
  LOG2EDependencies,
  LOG10EDependencies,
  SQRT2Dependencies,
  SQRT1_2Dependencies,
  InfinityDependencies,
  NaNDependencies,
  falseDependencies,
  trueDependencies,
  nullDependencies,
  // Expression tree & symbolic math
  parseDependencies,
  derivativeDependencies,
  simplifyDependencies,
  simplifyConstantDependencies,
  simplifyCoreDependencies,
  compileDependencies,
  evaluateDependencies,
  replacerDependencies,
  resolveDependencies,
  // AST nodes (most are pulled in transitively by parseDependencies)
  NodeDependencies,
  OperatorNodeDependencies,
  SymbolNodeDependencies,
  FunctionNodeDependencies,
  ConstantNodeDependencies,
  ArrayNodeDependencies,
  ParenthesisNodeDependencies,
  AccessorNodeDependencies,
  AssignmentNodeDependencies,
  BlockNodeDependencies,
  ConditionalNodeDependencies,
  FunctionAssignmentNodeDependencies,
  IndexNodeDependencies,
  ObjectNodeDependencies,
  RangeNodeDependencies,
  RelationalNodeDependencies,
  // Misc
  ResultSetDependencies,
  reviverDependencies,
} from "mathjs";

const baseDeps = {
  absDependencies,
  addDependencies,
  addScalarDependencies,
  subtractDependencies,
  subtractScalarDependencies,
  multiplyDependencies,
  multiplyScalarDependencies,
  divideDependencies,
  divideScalarDependencies,
  powDependencies,
  modDependencies,
  unaryMinusDependencies,
  unaryPlusDependencies,
  ceilDependencies,
  floorDependencies,
  roundDependencies,
  fixDependencies,
  signDependencies,
  equalDependencies,
  equalScalarDependencies,
  largerDependencies,
  smallerDependencies,
  largerEqDependencies,
  smallerEqDependencies,
  unequalDependencies,
  andDependencies,
  andTransformDependencies,
  orDependencies,
  orTransformDependencies,
  notDependencies,
  xorDependencies,
  expDependencies,
  expm1Dependencies,
  logDependencies,
  log1pDependencies,
  log2Dependencies,
  log10Dependencies,
  sqrtDependencies,
  cbrtDependencies,
  nthRootDependencies,
  nthRootsDependencies,
  squareDependencies,
  cubeDependencies,
  hypotDependencies,
  sinDependencies,
  cosDependencies,
  tanDependencies,
  asinDependencies,
  acosDependencies,
  atanDependencies,
  atan2Dependencies,
  secDependencies,
  cscDependencies,
  cotDependencies,
  asecDependencies,
  acscDependencies,
  acotDependencies,
  sinhDependencies,
  coshDependencies,
  tanhDependencies,
  asinhDependencies,
  acoshDependencies,
  atanhDependencies,
  sechDependencies,
  cschDependencies,
  cothDependencies,
  asechDependencies,
  acschDependencies,
  acothDependencies,
  gammaDependencies,
  lgammaDependencies,
  erfDependencies,
  factorialDependencies,
  combinationsDependencies,
  permutationsDependencies,
  gcdDependencies,
  lcmDependencies,
  reDependencies,
  imDependencies,
  argDependencies,
  conjDependencies,
  complexDependencies,
  ComplexDependencies,
  numberDependencies,
  fractionDependencies,
  FractionDependencies,
  numericDependencies,
  booleanDependencies,
  stringDependencies,
  BigNumberDependencies,
  bignumberDependencies,
  typeOfDependencies,
  cloneDependencies,
  formatDependencies,
  isIntegerDependencies,
  isNaNDependencies,
  isFiniteDependencies,
  isZeroDependencies,
  isNegativeDependencies,
  isPositiveDependencies,
  isNumericDependencies,
  hasNumericValueDependencies,
  isBoundedDependencies,
  minDependencies,
  maxDependencies,
  sumDependencies,
  detDependencies,
  traceDependencies,
  matrixDependencies,
  MatrixDependencies,
  DenseMatrixDependencies,
  SparseMatrixDependencies,
  EDependencies,
  PIDependencies,
  LN2Dependencies,
  LN10Dependencies,
  LOG2EDependencies,
  LOG10EDependencies,
  SQRT2Dependencies,
  SQRT1_2Dependencies,
  InfinityDependencies,
  NaNDependencies,
  falseDependencies,
  trueDependencies,
  nullDependencies,
  parseDependencies,
  derivativeDependencies,
  simplifyDependencies,
  simplifyConstantDependencies,
  simplifyCoreDependencies,
  compileDependencies,
  evaluateDependencies,
  replacerDependencies,
  resolveDependencies,
  NodeDependencies,
  OperatorNodeDependencies,
  SymbolNodeDependencies,
  FunctionNodeDependencies,
  ConstantNodeDependencies,
  ArrayNodeDependencies,
  ParenthesisNodeDependencies,
  AccessorNodeDependencies,
  AssignmentNodeDependencies,
  BlockNodeDependencies,
  ConditionalNodeDependencies,
  FunctionAssignmentNodeDependencies,
  IndexNodeDependencies,
  ObjectNodeDependencies,
  RangeNodeDependencies,
  RelationalNodeDependencies,
  ResultSetDependencies,
  reviverDependencies,
};

export function createInstance({
  define_e = true,
  define_pi = true,
  define_i = true,
  pow_strict = true,
} = {}) {
  const deps = { ...baseDeps };

  if (define_e) deps.eDependencies = eDependencies;
  if (define_pi) deps.piDependencies = piDependencies;
  if (define_i) deps.iDependencies = iDependencies;

  let math = create(deps);

  // strict power function that returns NaN for 0^0, NaN^0, and Infinity^0
  var pow_original = math.pow;
  function pow_strict_f(base, pow) {
    if (
      pow === 0 &&
      typeof base === "number" &&
      (base === 0 || !Number.isFinite(base))
    ) {
      return NaN;
    } else return pow_original(base, pow);
  }

  if (pow_strict) math["import"]({ pow: pow_strict_f }, { override: true });
  else math["import"]({ pow: pow_original }, { override: true });

  math.define_e = define_e;
  math.define_pi = define_pi;
  math.define_i = define_i;
  math.pow_strict = pow_strict;

  return math;
}

export default createInstance();
