//! Autogenerated fuzz tests (PORTING_PLAN.md §15 Phase 7, "differential test
//! harness"). NOT hand-written — `fixtures/autogenerated-fuzz-tests.json` is
//! produced by `scripts/generate-fuzz-tests.mjs`: a seeded grammar generates
//! random text expressions, the JS reference library is the oracle, and cases
//! are pruned to those whose operator/function signature is not already covered
//! by the hand-written and corpus tests (a bounded sample of the novel space —
//! see the generator header). Regenerate/rewiden with:
//!   node scripts/generate-fuzz-tests.mjs [seed]
//!
//! Three checks against the JS oracle:
//! - **parse fidelity** — `to_js(parse(input))` matches JS's `.tree` (the
//!   faithful layer must match byte-for-byte).
//! - **equals agreement** — Rust `equals(a,b)` matches JS's verdict.
//! - **hang resistance** — inputs on which JS `equals` *hangs* (a real infinite
//!   loop in its sampler, e.g. `abs(-pi) == 4`) must return quickly in Rust.
//!
//! These agree fully today (zero divergences), so any failure is a real
//! regression to investigate, not an expected-divergence snapshot to bump.

use math_expressions::{equals, js_tree, EqOptions, Expr, TextToAst, TextToAstOptions};
use serde_json::Value;
use std::time::{Duration, Instant};

fn parse(s: &str) -> Option<Expr> {
    TextToAst::new(TextToAstOptions::default()).convert(s).ok()
}

fn catch<T>(f: impl FnOnce() -> T) -> Option<T> {
    std::panic::catch_unwind(std::panic::AssertUnwindSafe(f)).ok()
}

#[derive(serde::Deserialize)]
struct Corpus {
    parse: Vec<ParseCase>,
    equals: Vec<EqualsCase>,
    #[serde(rename = "jsHangs")]
    js_hangs: Vec<HangCase>,
}

#[derive(serde::Deserialize)]
struct ParseCase {
    input: String,
    tree: Value,
}

#[derive(serde::Deserialize)]
struct EqualsCase {
    a: String,
    b: String,
    equal: bool,
}

#[derive(serde::Deserialize)]
struct HangCase {
    a: String,
    b: String,
}

const CORPUS: &str = include_str!("fixtures/autogenerated-fuzz-tests.json");

fn corpus() -> Corpus {
    serde_json::from_str(CORPUS).unwrap()
}

#[test]
fn parse_matches_js() {
    std::panic::set_hook(Box::new(|_| {}));
    let mut diffs = Vec::new();
    for c in &corpus().parse {
        let got = catch(|| parse(&c.input).map(|e| js_tree::to_js(&e))).flatten();
        if got.as_ref() != Some(&c.tree) {
            diffs.push(format!("  {:?}\n    JS:   {}\n    Rust: {:?}", c.input, c.tree, got));
        }
    }
    assert!(
        diffs.is_empty(),
        "{} parse divergence(s) from JS:\n{}",
        diffs.len(),
        diffs.join("\n"),
    );
}

#[test]
fn equals_matches_js() {
    std::panic::set_hook(Box::new(|_| {}));
    let opts = EqOptions::default();
    let mut diffs = Vec::new();
    for c in &corpus().equals {
        let verdict = catch(|| {
            let (a, b) = (parse(&c.a)?, parse(&c.b)?);
            Some(equals(&a, &b, &opts))
        })
        .flatten();
        if verdict != Some(c.equal) {
            diffs.push(format!("  {:?} == {:?}: JS {} vs Rust {:?}", c.a, c.b, c.equal, verdict));
        }
    }
    assert!(
        diffs.is_empty(),
        "{} equals divergence(s) from JS:\n{}",
        diffs.len(),
        diffs.join("\n"),
    );
}

/// Inputs on which JS `equals` hangs (never returns) must be handled promptly by
/// Rust. A generous per-call budget catches a regression into a slow/looping
/// path without being flaky; today each returns in well under a millisecond.
#[test]
fn does_not_hang_where_js_does() {
    let opts = EqOptions::default();
    for c in &corpus().js_hangs {
        let (a, b) = (parse(&c.a).unwrap(), parse(&c.b).unwrap());
        let t = Instant::now();
        let _ = equals(&a, &b, &opts);
        let elapsed = t.elapsed();
        assert!(
            elapsed < Duration::from_secs(2),
            "equals({:?}, {:?}) took {:?} — JS hangs here; Rust must stay responsive",
            c.a,
            c.b,
            elapsed,
        );
    }
}
