//! Deterministic parser enumeration (PARSER_FUEL_PLAN.md, Part B2).
//!
//! Systematic — **not random** — coverage of the malformed-input space. Every
//! input below is generated by a fixed rule in a fixed order, so each run
//! parses exactly the same strings and any failure is reproducible. There is no
//! RNG, no seed, no `proptest`.
//!
//! The property under test is termination: for BOTH parsers, every generated
//! input returns (`Ok` or `Err`) without panicking. The parse-fuel backstop
//! (`ResourceLimits::max_parse_steps` + a `tick()` in every loop) is what
//! guarantees the return; this suite proves it across a broad, fixed space.
//!
//! Three enumerators:
//!   1. truncation sweep  — every prefix of known-good expressions (mechanically
//!      produces every half-open construct: `\begin{bmatrix}`, `\frac{`, …);
//!   2. bounded exhaustive — all token sequences up to length `MAX_LEN` over a
//!      curated "dangerous token" alphabet;
//!   3. single-edit mutations — every deletion and dangerous-char insertion of
//!      each seed.

use math_expressions::resource_limits::{self, ResourceLimits};
use math_expressions::{LatexToAst, LatexToAstOptions, TextToAst, TextToAstOptions};

/// Parse `s` with both parsers; fail (with the offending input) on a panic.
/// Both parsers always *return* — every parser loop consumes fuel — so this
/// never hangs; it only guards against panics and proves the whole fixed space
/// terminates.
///
/// Run under a small scoped fuel budget so a would-spin input aborts in
/// microseconds instead of grinding to the multi-million-step default cap:
/// the property is termination, which a tiny budget proves just as well and
/// keeps the exhaustive sweep fast. Valid short inputs use far fewer steps.
fn check(s: &str) {
    let budget = ResourceLimits {
        max_parse_steps: 50_000,
        ..ResourceLimits::default()
    };
    let panicked = resource_limits::with(budget, || {
        let t = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            let _ = TextToAst::new(TextToAstOptions::default()).convert(s);
        }))
        .is_err();
        let l = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            let _ = LatexToAst::new(LatexToAstOptions::default()).convert(s);
        }))
        .is_err();
        t || l
    });
    assert!(!panicked, "a parser panicked on {s:?}");
}

/// Known-good expressions (text + LaTeX) whose prefixes / mutations are swept.
const SEEDS: &[&str] = &[
    r"\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}",
    r"\frac{x + 1}{y - 2}",
    r"\sqrt[3]{x^2 + 1}",
    r"\left( \frac{1}{2} \right)",
    "sin^2(x) + cos^2(x)",
    "(a + b)*(c - d)/e",
    "|x - 1| + |y|",
    "x_1 + x_2^3",
    "1.5 + 2/3 - 4^5",
];

/// Enumerator 1 — parse EVERY prefix of each seed (char-boundary safe).
#[test]
fn truncation_sweep_terminates() {
    for &seed in SEEDS {
        for i in 0..=seed.len() {
            if seed.is_char_boundary(i) {
                check(&seed[..i]);
            }
        }
    }
}

/// Curated alphabet of tokens that drive the parser's loops and delimiter logic.
const TOKENS: &[&str] = &[
    "(", ")", "{", "}", "!", "^", "_", "&", r"\\", r"\begin{bmatrix}",
    r"\end{bmatrix}", "1", "x",
];
const MAX_LEN: usize = 3; // |TOKENS|^1 + ^2 + ^3 = 13 + 169 + 2197 = 2379 inputs

/// Enumerator 2 — every token sequence up to `MAX_LEN`, in odometer order.
#[test]
fn bounded_exhaustive_terminates() {
    let n = TOKENS.len();
    for len in 1..=MAX_LEN {
        let total = n.pow(len as u32);
        for combo in 0..total {
            let mut s = String::new();
            let mut idx = combo;
            for _ in 0..len {
                s.push_str(TOKENS[idx % n]);
                idx /= n;
            }
            check(&s);
        }
    }
}

const INSERT_CHARS: &[char] = &['(', '{', '&', '^', '\\', '!', '}'];

/// Enumerator 3 — every single-char deletion and dangerous-char insertion of
/// each seed (a full, ordered sweep — no random choice).
#[test]
fn single_edit_mutations_terminate() {
    for &seed in SEEDS {
        // Deletions: drop each character in turn.
        for (i, ch) in seed.char_indices() {
            let mut m = String::with_capacity(seed.len());
            m.push_str(&seed[..i]);
            m.push_str(&seed[i + ch.len_utf8()..]);
            check(&m);
        }
        // Insertions: insert each dangerous char at every boundary.
        for i in 0..=seed.len() {
            if !seed.is_char_boundary(i) {
                continue;
            }
            for &c in INSERT_CHARS {
                let mut m = String::with_capacity(seed.len() + 1);
                m.push_str(&seed[..i]);
                m.push(c);
                m.push_str(&seed[i..]);
                check(&m);
            }
        }
    }
}
